### PR TITLE
NEW add react drive font selection field with preview

### PR DESCRIPTION
**Pull request by NightJar**
to coincide with theme options selection work, there is now a
corresponding font picker that will live update some preview text to
show the administrator an example of that font, giving a richer
experience than a simple dropdown field.

### CODE REVIEW

**Comment by scott1702** [comment]
Thanks @NightJar, I rebased and manually merged this in as I didn't have access to CCs repo https://github.com/spaceship-operators/cwp-agencyextensions/commits/feature/color-picker-field

**Comment by NightJar** [comment]
@scott1702 ah cool, ta. There was one outstanding thing left to do though - that was to have the font picker show the default selection without having to trigger an update first. Currently when loading the page the font preview is incorrect, and not until the user selects another font does it update to show an actual preview.

James also wished to have the preview text have one line of the full alphabet (symbols, numbers, & all), and then a second line with an example bit of text (such as the current one). Are you cool with that, or should I make another PR?

**Comment by scott1702** [comment]
@NightJar I've got some time to clean up everything today so I can jump across it, cheers for the heads up!

**Comment by NightJar** [comment]
For reference about the preview text:
I was going to make a _second_ translatable string to contain the alphabet - this way the preview and the alphabet can be updated individually (and re-ordered so the preview is atop the alphabet if I've remembered the ordering wrong) easily :)

**Pull request closed without merging**
